### ISSUE TITLE
City of Brains

### ISSUE THREAD

**Issue by patcon** [CivicTechTO/project-tracker#4]

**Comment by patcon** [comment]
``` yml
- date: 2016-06-08
  name: City of Brains
  description: ux
  lead: mark
```
