### ISSUE TITLE
Public Art mapping

### ISSUE THREAD

**Issue by patcon** [CivicTechTO/project-tracker#9]

**Comment by patcon** [comment]
``` yml
- date: 2016-06-08
  name: Public Art mapping
  description: discussion
  lead: raphael
```
